variables:
  DIST_DIR: /home/www/wwwroot/vite-front
before_script:
  - mkdir -p ${DIST_DIR}
stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules
    - dist
install-job:
  only:
    refs:
      - master
  tags:
    - build,deploy
  stage: install
  script: 
    - npm install
  
build-job:
  tags:
    - build,deploy
  stage: build
  script:
    - npm run build

deploy-job:
  only:
    refs:
      - master
  tags:
    - build,deploy
  stage: deploy
  script:
    - rm -rf ${DIST_DIR}/*
    - cp -rf dist/* ${DIST_DIR}/
